fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
    powershell:
      repo: 'https://github.com/puppetlabs/puppetlabs-powershell.git'
      ref: '1.0.6'
  symlinks:
    windows_domain_controller: "#{source_dir}"
