name    'martezr-windows_domain_controller'
version '0.1.0'
source 'https://github.com/martezr/puppet-windows_domain_controller.git'
author 'Martez Reed'
license ''
summary 'Puppet module to install active directory domain services'
description 'Puppet module to install active directory domain services'
project_page 'https://github.com/martezr/puppet-windows_domain_controller'

dependency 'joshcooper/powershell', '0.0.6'
dependency 'puppetlabs/stdlib', '4.1.0'
