name    'martezr-windows_domain_controller'
version '0.1.3'
source 'https://github.com/martezr/puppet-windows_domain_controller.git'
author 'Martez Reed'
license 'Apache License, Version 2.0'
summary 'Puppet module to install active directory domain services'
description 'Puppet module to install active directory domain services'
project_page 'https://github.com/martezr/puppet-windows_domain_controller'

dependency 'joshcooper/powershell'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
